# Generated by Django 3.2 on 2022-06-08 17:31

import client.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailListUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('mail_title', models.TextField(max_length=80)),
                ('mail_text', models.TextField(max_length=320)),
                ('upload_description', models.CharField(max_length=80)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('spreadsheet', models.FileField(upload_to='')),
                ('sender_email', models.EmailField(max_length=254)),
                ('success_count', models.IntegerField(default=0, editable=False)),
                ('success_file', models.FileField(blank=True, editable=False, null=True, upload_to=client.models.email_upload_status_file_path)),
                ('failure_count', models.IntegerField(default=0, editable=False)),
                ('failure_file', models.FileField(blank=True, editable=False, null=True, upload_to=client.models.email_upload_status_file_path)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Processing', editable=False, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailReceipientRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('recipient_name', models.CharField(max_length=50)),
                ('reciever_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], editable=False, max_length=30)),
                ('intended_message', models.CharField(max_length=50, null=True)),
                ('status_message', models.CharField(max_length=50, null=True)),
                ('email_upload_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.emaillistupload')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
